import cx_Oracle
from time import perf_counter
# Connection parameters
dsn_tns = cx_Oracle.makedsn('localhost', 1521, service_name='free')
connection = cx_Oracle.connect(user='c##trial', password='trialtest', dsn=dsn_tns)
cursor = connection.cursor()

try:   
    
    # Define the CREATE TABLE SQL statement
    create_table_query = """    
    CREATE TABLE employeesone (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(100),
        position VARCHAR2(50),
        salary NUMBER(10, 2),
        hire_date DATE DEFAULT SYSDATE
    )
    """
    start = perf_counter()

    #drop_table_query = "DROP TABLE employeesone"
    # Execute the query
    cursor.execute(create_table_query)
    end = perf_counter()
    print(f"Table 'employeesone' dropped successfully in {round(end - start, 3)}.")

except cx_Oracle.DatabaseError as e:
    print("Error while dropped table:", e)
finally:
    # Close the cursor and connection
    cursor.close()
    connection.close()
